title = "Greenhorn 2024"
baseURL = "//greenhorn-meeting.net/2024/"
tags = ["greenhorn", "meeting", "academia", "university", "siegen", "master", "phd", "optics", "ions"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
relativeURLs=false
canonifyURLs=true
googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
  tagline = ""
  author = ""
  description = "The annual greenhorn meeting, 2024 at the university of Siegen"
  logoBig = "/images/logo.png"
  logoSmall = "/images/logo.png"
  #favicon = "favicon.ico"
  #opengraphImage = "/images/osprey.png"
  email = ""
  googleTagManger = ""
  customCSS = false

  # Copyright and theme author credit in footer
  copyright = false
  credit = false

  # Cache busting of static resources (additional set up required)
  cacheBustCSS = false
  cacheBustJS = false

  # Code highlighting with highlight.js
  highlightJS = true
  highlightJSStyle = "" # For custom highlight.js styles, add your /path/to/styles/default.css
  highlightJSScript = "" # For custom highlight.js languages config, add your /path/to/highlight.pack.js

  # Choose either Formspree contact form or Basin contact form
  ajaxFormspree = false
  ajaxFormspreeGold = false
  ajaxBasin = false

  # Lazy loading with lazysizes
  lazyloading = true

[[menu.main]]
  name = "About"
  url  = "/#about"
  weight = 1
[[menu.main]]
  name = "Venue"
  url  = "/#venue"
  weight = 2
[[menu.main]]
  name = "Registration"
  url  = "/#registration"
  weight = 3
[[menu.main]]
  name = "Contact"
  url  = "/#contact"
  weight = 4
