title = "Osprey Example Site"
baseURL = "https://tomanistor.com"
tags = ["portfolio", "web design", "blog"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = "tomanistor"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
  tagline = "Osprey Example Site"
  author = "Toma Nistor"
  description = "Full-stack web developer and UI/UX enthusiast based in San Diego, CA."
  logoBig = "/images/logo.png"
  logoSmall = "/images/logo.png"
  favicon = "favicon.ico"
  opengraphImage = "/images/osprey.png"
  email = ""
  googleTagManger = ""
  customCSS = false

  # Copyright and theme author credit in footer
  copyright = false
  credit = false

  # Cache busting of static resources (additional set up required)
  cacheBustCSS = false
  cacheBustJS = false

  # Code highlighting with highlight.js
  highlightJS = true
  highlightJSStyle = "" # For custom highlight.js styles, add your /path/to/styles/default.css
  highlightJSScript = "" # For custom highlight.js languages config, add your /path/to/highlight.pack.js

  # Choose either Formspree contact form or Basin contact form
  ajaxFormspree = false
  ajaxFormspreeGold = false
  ajaxBasin = false

  # Lazy loading with lazysizes
  lazyloading = true

[[menu.main]]
  name = "About"
  url  = "/#about"
  weight = 1
[[menu.main]]
  name = "Venue"
  url  = "/#venue"
  weight = 2
[[menu.main]]
  name = "Registration"
  url  = "/#registration"
  weight = 3
[[menu.main]]
  name = "Contact"
  url  = "/#contact"
  weight = 4
